Fix Test Chamber 13 Escape Hatch cutscene triggers (issue #10)
mwpenny/portal64-still-alive pull request #12
Opened 2024-02-23 14:35 UTC by Deconimus

See Issue #10 

* If the player is inside the side_room without a cube, they can still stand on the button and shoot a portal through the door. `trapped` is therefore never reached if the player is inside the side_room.
* The old `main_cube_access` is redundant, as the main room can always be accessed as long as the player is not inside the exit corridor with the exit door closed. This also fixes the cutscene from triggering if the player exits the chamber normally as described.
* Trapping the first cube in the side_room without the side_room door being open doesn't trigger the cutscene anymore, just like in the original game. The player can still stand on one of the buttons.
* Trapping both cubes in the side_room without the door being open and the player being in the main_room does trigger the cutscene as it should.
* Trapping both cubes in the exit corridor triggers the cutscene as it should.

2024-02-23 16:06 UTC, mwpenny requested changes
Great work and write-up. The new conditions make sense.

Just two minor things worth tweaking.

2024-02-23 16:06 UTC, mwpenny commented on assets/test_chambers/test_chamber_08/test_chamber_08.yaml
> +  - side_cube_access_direct = player_in_side and has_cube_side
Since `has_cube_side` is used to define both side cube signals, could you simplify slightly to something like
```yaml
- side_room_access = player_in_side or room_enter
- side_cube_access = has_cube_side and side_room_access
```

Makes it a bit more clear.

2024-02-23 16:06 UTC, mwpenny commented on assets/test_chambers/test_chamber_08/test_chamber_08.yaml
>      - set_signal room_exit
Something your issue yesterday got me thinking about:

The `set_signal` cutscene step works by changing the default signal state, and other signal emitters (like operators) just invert the default state. `room_exit` is the same signal set below based on the buttons. So if a player gets trapped and the default gets changed here, then putting the cubes back on the buttons will actually close the door.

This can be avoided by using a separate signal for being trapped, and ORing it with the regular exit condition to determine if the door should open. Then if trapped, using the buttons will have no effect. This is how chamber 5 works (map names are not necessarily the same as chamber names, by the way):
https://github.com/mwpenny/portal64-still-alive/blob/c90b8ba42871d0f951ef2ed62e85b96b787791cf/assets/test_chambers/test_chamber_02/test_chamber_02.yaml#L28-L29

Can you make a similar change while you're here?

2024-02-23 16:57 UTC, Deconimus commented on assets/test_chambers/test_chamber_08/test_chamber_08.yaml
> +  - side_cube_access_direct = player_in_side and has_cube_side
I agree, this simplifies it.

See: https://github.com/mwpenny/portal64-still-alive/pull/12/commits/591e5958aa404875188a01d937faf571934565d3

2024-02-23 16:59 UTC, Deconimus commented on assets/test_chambers/test_chamber_08/test_chamber_08.yaml
>      - set_signal room_exit
I was able to reproduce this too, the change you proposed seems to fix this.

2024-02-24 17:29 UTC, mwpenny approved these changes

2024-02-24 17:30 UTC, merged