Decouple time interface from libultra
mwpenny/portal64-still-alive pull request #66
Opened 2024-05-11 13:07 UTC by GiacomoGarbin

PR for issue #65.

2024-05-14 03:14 UTC, mwpenny requested changes
Regarding your question in your first commit message:
> TODO: should we move time.h and time_libultra.c to the src/system folder?

Yes, let's follow the same pattern as we did for the controller.

2024-05-14 03:14 UTC, mwpenny commented on src/savefile/savefile.c
> +#define SRAM_CHUNK_DELAY (10 * 1000)
Minor: can you include the units in the name (i.e., `SRAM_CHUNK_DELAY_USECS`)? Makes it unambiguous to readers.

2024-05-14 03:14 UTC, mwpenny commented on src/savefile/savefile.c
> +    timeInit();
Sleeping is only used here, but the time system as a whole is unrelated to the savefile. Can you move initialization to `main()`?

2024-05-14 20:04 UTC, GiacomoGarbin commented
> Yes, let's follow the same pattern as we did for the controller.

Done in [0f6052a](https://github.com/mwpenny/portal64-still-alive/pull/66/commits/0f6052a9ae46c2acb607b5c6d7b3defb5a993bbd).

Thanks for the review! I had also considered the points you suggested.

2024-05-17 05:08 UTC, mwpenny commented
Great, thanks!

2024-05-17 05:09 UTC, merged